// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MULTICHANNELDATA_H_
#define FLATBUFFERS_GENERATED_MULTICHANNELDATA_H_

#include "flatbuffers/flatbuffers.h"

struct MultichannelData;
struct MultichannelDataBuilder;

struct MultichannelData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MultichannelDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SAMPLES = 4,
    VT_NBR_CHANNELS = 6,
    VT_NBR_SAMPLES = 8,
    VT_TIMESTAMPS = 10,
    VT_SAMPLE_RATE = 12,
    VT_PACKETID = 14,
    VT_STREAMID = 16
  };
  const flatbuffers::Vector<int8_t> *samples() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_SAMPLES);
  }
  int32_t nbr_channels() const {
    return GetField<int32_t>(VT_NBR_CHANNELS, 0);
  }
  int32_t nbr_samples() const {
    return GetField<int32_t>(VT_NBR_SAMPLES, 0);
  }
  int64_t timestamps() const {
    return GetField<int64_t>(VT_TIMESTAMPS, 0);
  }
  int32_t sample_rate() const {
    return GetField<int32_t>(VT_SAMPLE_RATE, 0);
  }
  int32_t packetid() const {
    return GetField<int32_t>(VT_PACKETID, 0);
  }
  int32_t streamid() const {
    return GetField<int32_t>(VT_STREAMID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SAMPLES) &&
           verifier.VerifyVector(samples()) &&
           VerifyField<int32_t>(verifier, VT_NBR_CHANNELS) &&
           VerifyField<int32_t>(verifier, VT_NBR_SAMPLES) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMPS) &&
           VerifyField<int32_t>(verifier, VT_SAMPLE_RATE) &&
           VerifyField<int32_t>(verifier, VT_PACKETID) &&
           VerifyField<int32_t>(verifier, VT_STREAMID) &&
           verifier.EndTable();
  }
};

struct MultichannelDataBuilder {
  typedef MultichannelData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_samples(flatbuffers::Offset<flatbuffers::Vector<int8_t>> samples) {
    fbb_.AddOffset(MultichannelData::VT_SAMPLES, samples);
  }
  void add_nbr_channels(int32_t nbr_channels) {
    fbb_.AddElement<int32_t>(MultichannelData::VT_NBR_CHANNELS, nbr_channels, 0);
  }
  void add_nbr_samples(int32_t nbr_samples) {
    fbb_.AddElement<int32_t>(MultichannelData::VT_NBR_SAMPLES, nbr_samples, 0);
  }
  void add_timestamps(int64_t timestamps) {
    fbb_.AddElement<int64_t>(MultichannelData::VT_TIMESTAMPS, timestamps, 0);
  }
  void add_sample_rate(int32_t sample_rate) {
    fbb_.AddElement<int32_t>(MultichannelData::VT_SAMPLE_RATE, sample_rate, 0);
  }
  void add_packetid(int32_t packetid) {
    fbb_.AddElement<int32_t>(MultichannelData::VT_PACKETID, packetid, 0);
  }
  void add_streamid(int32_t streamid) {
    fbb_.AddElement<int32_t>(MultichannelData::VT_STREAMID, streamid, 0);
  }
  explicit MultichannelDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MultichannelData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MultichannelData>(end);
    return o;
  }
};

inline flatbuffers::Offset<MultichannelData> CreateMultichannelData(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> samples = 0,
    int32_t nbr_channels = 0,
    int32_t nbr_samples = 0,
    int64_t timestamps = 0,
    int32_t sample_rate = 0,
    int32_t packetid = 0,
    int32_t streamid = 0) {
  MultichannelDataBuilder builder_(_fbb);
  builder_.add_timestamps(timestamps);
  builder_.add_streamid(streamid);
  builder_.add_packetid(packetid);
  builder_.add_sample_rate(sample_rate);
  builder_.add_nbr_samples(nbr_samples);
  builder_.add_nbr_channels(nbr_channels);
  builder_.add_samples(samples);
  return builder_.Finish();
}

inline flatbuffers::Offset<MultichannelData> CreateMultichannelDataDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int8_t> *samples = nullptr,
    int32_t nbr_channels = 0,
    int32_t nbr_samples = 0,
    int64_t timestamps = 0,
    int32_t sample_rate = 0,
    int32_t packetid = 0,
    int32_t streamid = 0) {
  auto samples__ = samples ? _fbb.CreateVector<int8_t>(*samples) : 0;
  return CreateMultichannelData(
      _fbb,
      samples__,
      nbr_channels,
      nbr_samples,
      timestamps,
      sample_rate,
      packetid,
      streamid);
}

inline const MultichannelData *GetMultichannelData(const void *buf) {
  return flatbuffers::GetRoot<MultichannelData>(buf);
}

inline const MultichannelData *GetSizePrefixedMultichannelData(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<MultichannelData>(buf);
}

inline bool VerifyMultichannelDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MultichannelData>(nullptr);
}

inline bool VerifySizePrefixedMultichannelDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MultichannelData>(nullptr);
}

inline void FinishMultichannelDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MultichannelData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMultichannelDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MultichannelData> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_MULTICHANNELDATA_H_
