// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EVENTDATA_H_
#define FLATBUFFERS_GENERATED_EVENTDATA_H_

#include "flatbuffers/flatbuffers.h"

struct EventData;
struct EventDataBuilder;

struct EventData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef EventDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVENTS = 4,
    VT_TIMESTAMPS = 6,
    VT_PACKETID = 8,
    VT_STREAMID = 10
  };
  const flatbuffers::String *events() const {
    return GetPointer<const flatbuffers::String *>(VT_EVENTS);
  }
  int64_t timestamps() const {
    return GetField<int64_t>(VT_TIMESTAMPS, 0);
  }
  int32_t packetid() const {
    return GetField<int32_t>(VT_PACKETID, 0);
  }
  int32_t streamid() const {
    return GetField<int32_t>(VT_STREAMID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_EVENTS) &&
           verifier.VerifyString(events()) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMPS) &&
           VerifyField<int32_t>(verifier, VT_PACKETID) &&
           VerifyField<int32_t>(verifier, VT_STREAMID) &&
           verifier.EndTable();
  }
};

struct EventDataBuilder {
  typedef EventData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_events(flatbuffers::Offset<flatbuffers::String> events) {
    fbb_.AddOffset(EventData::VT_EVENTS, events);
  }
  void add_timestamps(int64_t timestamps) {
    fbb_.AddElement<int64_t>(EventData::VT_TIMESTAMPS, timestamps, 0);
  }
  void add_packetid(int32_t packetid) {
    fbb_.AddElement<int32_t>(EventData::VT_PACKETID, packetid, 0);
  }
  void add_streamid(int32_t streamid) {
    fbb_.AddElement<int32_t>(EventData::VT_STREAMID, streamid, 0);
  }
  explicit EventDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<EventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<EventData>(end);
    return o;
  }
};

inline flatbuffers::Offset<EventData> CreateEventData(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> events = 0,
    int64_t timestamps = 0,
    int32_t packetid = 0,
    int32_t streamid = 0) {
  EventDataBuilder builder_(_fbb);
  builder_.add_timestamps(timestamps);
  builder_.add_streamid(streamid);
  builder_.add_packetid(packetid);
  builder_.add_events(events);
  return builder_.Finish();
}

inline flatbuffers::Offset<EventData> CreateEventDataDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *events = nullptr,
    int64_t timestamps = 0,
    int32_t packetid = 0,
    int32_t streamid = 0) {
  auto events__ = events ? _fbb.CreateString(events) : 0;
  return CreateEventData(
      _fbb,
      events__,
      timestamps,
      packetid,
      streamid);
}

inline const EventData *GetEventData(const void *buf) {
  return flatbuffers::GetRoot<EventData>(buf);
}

inline const EventData *GetSizePrefixedEventData(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<EventData>(buf);
}

inline bool VerifyEventDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<EventData>(nullptr);
}

inline bool VerifySizePrefixedEventDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<EventData>(nullptr);
}

inline void FinishEventDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<EventData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEventDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<EventData> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_EVENTDATA_H_
