name: Format and Compile

on:
  pull_request:
    branches: [develop]

jobs:
  build-linux:
    name: Format and Compile
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        compiler: [clang] # gcc is disabled for now

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone falcon-core repository
        run: |
          cd ..
          git clone --depth 1 https://github.com/falcon-eyrie/falcon-core.git
          cd falcon-core
          git checkout develop
          cd ..

          # Copy current repo into falcon-core/extensions
          mkdir -p falcon-core/extensions
          cp -a falcon-fklab-extensions falcon-core/extensions/

      - name: Install dependencies
        run: |
          sh scripts/setup/install_deps.sh
          sh scripts/setup/install_cmake.sh
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            sh scripts/setup/install_llvm.sh
          fi

      - name: Run clang-format (only for clang)
        if: matrix.compiler == 'clang'
        run: |
          sh scripts/format.sh
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Following files seem to be not formatted. Please run './scripts/format.sh' locally and commit the changes."
            git --no-pager diff --name-only
            exit 1
          fi

      - name: Configure CMake
        run: |
          cd ../falcon-core
          mkdir -p build
          cd build
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            C_PATH=/usr/local/bin/clang
            CXX_PATH=/usr/local/bin/clang++
          else
            C_PATH=/usr/bin/gcc
            CXX_PATH=/usr/bin/g++
          fi
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=$C_PATH \
            -DCMAKE_CXX_COMPILER=$CXX_PATH

      - name: Build project
        run: |
          cd ../falcon-core/build
          make -j$(nproc)

      # Clang tidy is not yet enabled for the project
      # - name: Run clang-tidy (only for clang)
      #   if: matrix.compiler == 'clang'
      #   run: |
      #     sh scripts/tidy.sh
